UI for private-app guide
CartoDB/viz-doc pull request #35
Opened 2023-05-30 14:45 UTC by vmilan

UI adaptation of private-app demo guide.

2023-05-30 15:12 UTC, VictorVelarde approved these changes
👍🏻 LGTM Vero, thx

2023-05-30 16:06 UTC, alasarr requested changes

2023-05-30 16:06 UTC, alasarr commented on guides/private-app/src/main.ts
> -import './style.css'
Keep this because it works like this in other places like public-app and templates. And I've a step by step guide that I will need to change

2023-05-30 16:06 UTC, alasarr commented on guides/private-app/src/main.ts
> -document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
Same, keep the HTML code here

2023-05-30 16:06 UTC, alasarr commented on guides/private-app/static/styles.css
> +/*************************
Keep it in src

2023-05-30 16:10 UTC, alasarr requested changes
Looks good, but it changes the structure of files and I want to keep the current one because it's the structure used by the Vite template (`npm create vite@latest`)

2023-05-31 11:25 UTC, alasarr approved these changes

2023-05-31 11:25 UTC, merged

2023-05-31 11:25 UTC, alasarr commented
Thanks a lot!